### ISSUE TITLE
Would you like to provide a demo to use pysmilesutils for downstream examples?

### ISSUE THREAD

**Issue by xuzhang5788** [MolecularAI/pysmilesutils#1]
Thank you so much for your repo. If you could give us a tutorial on how to use pysmilesutils in real applications, that will be a great help. 
I think you knew selfies well. Is it possible to substitute smiles with selfies?

**Comment by SGenheden** [comment]
Hello

Thank you for trying out pysmilesutils.

There is an `example` folder in the base-folder of the repository with several examples. These can be view in VSCode or converted to Jupyter notebook.

We have no plans to support selfies at the moment. If you think it is of interest, we welcome the discussion in another issue.

**Comment by EBjerrum** [comment]
I'm not fully into the SELFIES syntax, but I think it should be possible to modify the regular expression pattern and otherwise use the tokenizer class to build the vocabulary and tokenize.

**Comment by xuzhang5788** [comment]
Thank you very much!
